### ISSUE TITLE
Wrong Type on macOS

### ISSUE THREAD

**Issue by sparkylein** [nuxui/nuxui#2]
Tried to compile on macOS, this is the error message:
> nuxui.org/nuxui/nux/internal/darwin
internal/darwin/NSEvent.go:112:68: invalid operation: (_Cfunc_nux_NSEvent_HasPreciseScrollingDeltas)(_Ctype_uintptr_t(me)) > 0 (mismatched types _Ctype__Bool and untyped int)
internal/darwin/NSEvent.go:132:52: invalid operation: (_Cfunc_nux_NSEvent_IsARepeat)(_Ctype_uintptr_t(me)) > 0 (mismatched types _Ctype__Bool and untyped int)
internal/darwin/NSPanel.go:110:7: cannot use 1 (untyped int constant) as _Ctype__Bool value in assignment
internal/darwin/NSPanel.go:118:7: cannot use 1 (untyped int constant) as _Ctype__Bool value in assignment
internal/darwin/NSPanel.go:126:7: cannot use 1 (untyped int constant) as _Ctype__Bool value in assignment
internal/darwin/NSPanel.go:142:7: cannot use 1 (untyped int constant) as _Ctype__Bool value in assignment

Keep up the good work!

**Comment by nuxart** [comment]
@sparkylein What operating system and processor architecture are you using (go env)?
```
$ go env
```

**Comment by nuxart** [comment]
@sparkylein  Can you try below codes, did these changes works? I'm not sure it works in your environment

file `NSPanel.go`
``` diff
func (me NSOpenPanel) SetCanChooseFiles(can bool) {
 	var b C.BOOL
 	if can {
-		b = 1
+		b = C.BOOL(1)
 	}
 	C.nux_NSOpenPanel_setCanChooseFiles(C.uintptr_t(me), b)
 }

 func (me NSOpenPanel) SetCanChooseDirectories(can bool) {
 	var b C.BOOL
 	if can {
-		b = 1
+		b = C.BOOL(1)
 	}
 	C.nux_NSOpenPanel_setCanChooseDirectories(C.uintptr_t(me), b)
 }


 func (me NSOpenPanel) SetAllowsMultipleSelection(allow bool) {
 	var b C.BOOL
 	if allow {
-		b = 1
+		b = C.BOOL(1)
 	}
 	C.nux_NSOpenPanel_setAllowsMultipleSelection(C.uintptr_t(me), b)
 }


 func (me NSOpenPanel) SetCanCreateDirectories(can bool) {
 	var b C.BOOL
 	if can {
-		b = 1
+		b = C.BOOL(1)
 	}
 	C.nux_NSOpenPanel_setCanCreateDirectories(C.uintptr_t(me), b)
 }

```

file `NSEvent.m`
```diff
-BOOL nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent){
-  return [(NSEvent *)nsevent hasPreciseScrollingDeltas];
+int nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent){
+  return  (int)( [(NSEvent *)nsevent hasPreciseScrollingDeltas]);
 }


-BOOL nux_NSEvent_IsARepeat(uintptr_t nsevent){
-  return [(NSEvent *)nsevent isARepeat];
+int nux_NSEvent_IsARepeat(uintptr_t nsevent){
+  return (int)([(NSEvent *)nsevent isARepeat]);

```

file `NSEvent.go`

```diff

-BOOL           nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent);
+int            nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent);

-BOOL           nux_NSEvent_IsARepeat(uintptr_t nsevent);
+int            nux_NSEvent_IsARepeat(uintptr_t nsevent);


```

**Comment by bashery** [comment]
on macos m1 i try

```go 
if can {
	b = true
 }
```
and 
```go
func (me NSEvent) HasPreciseScrollingDeltas() bool {
	return C.nux_NSEvent_HasPreciseScrollingDeltas(C.uintptr_t(me)) == false
}
```
and evrything is work fine

**Comment by nuxart** [comment]
@bashery it looks you can use go `bool` for cgo directly, when I direct use go `bool` in cgo, it shows :
`cannot use true (untyped bool constant) as _Ctype_schar value in argument to (_Cfunc_nux_NSOpenPanel_setCanChooseFiles)`

Can you try this solution, did it works on m1? 


> @sparkylein Can you try below codes, did these changes works? I'm not sure it works in your environment
> 
> file `NSPanel.go`
> 
> ```diff
> func (me NSOpenPanel) SetCanChooseFiles(can bool) {
>  	var b C.BOOL
>  	if can {
> -		b = 1
> +		b = C.BOOL(1)
>  	}
>  	C.nux_NSOpenPanel_setCanChooseFiles(C.uintptr_t(me), b)
>  }
> 
>  func (me NSOpenPanel) SetCanChooseDirectories(can bool) {
>  	var b C.BOOL
>  	if can {
> -		b = 1
> +		b = C.BOOL(1)
>  	}
>  	C.nux_NSOpenPanel_setCanChooseDirectories(C.uintptr_t(me), b)
>  }
> 
> 
>  func (me NSOpenPanel) SetAllowsMultipleSelection(allow bool) {
>  	var b C.BOOL
>  	if allow {
> -		b = 1
> +		b = C.BOOL(1)
>  	}
>  	C.nux_NSOpenPanel_setAllowsMultipleSelection(C.uintptr_t(me), b)
>  }
> 
> 
>  func (me NSOpenPanel) SetCanCreateDirectories(can bool) {
>  	var b C.BOOL
>  	if can {
> -		b = 1
> +		b = C.BOOL(1)
>  	}
>  	C.nux_NSOpenPanel_setCanCreateDirectories(C.uintptr_t(me), b)
>  }
> ```
> 
> file `NSEvent.m`
> 
> ```diff
> -BOOL nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent){
> -  return [(NSEvent *)nsevent hasPreciseScrollingDeltas];
> +int nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent){
> +  return  (int)( [(NSEvent *)nsevent hasPreciseScrollingDeltas]);
>  }
> 
> 
> -BOOL nux_NSEvent_IsARepeat(uintptr_t nsevent){
> -  return [(NSEvent *)nsevent isARepeat];
> +int nux_NSEvent_IsARepeat(uintptr_t nsevent){
> +  return (int)([(NSEvent *)nsevent isARepeat]);
> ```
> 
> file `NSEvent.go`
> 
> ```diff
> -BOOL           nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent);
> +int            nux_NSEvent_HasPreciseScrollingDeltas(uintptr_t nsevent);
> 
> -BOOL           nux_NSEvent_IsARepeat(uintptr_t nsevent);
> +int            nux_NSEvent_IsARepeat(uintptr_t nsevent);
> ```

**Comment by bashery** [comment]
Hi @nuxart 
First I tried that solution, it was returning this error.
<img width="785" alt="Screen Shot 2022-07-29 at 17 01 03" src="https://user-images.githubusercontent.com/48377058/181777447-31be616c-a63c-4922-a5f1-b2e479103977.png">

Then I tried go ```bool``` directly and it worked fine.
But with the modification on : 
<img width="622" alt="Screen Shot 2022-07-29 at 17 12 39" src="https://user-images.githubusercontent.com/48377058/181778876-f90bc63d-339e-4073-8f5f-58dcf1c90cd9.png">
and 
<img width="478" alt="Screen Shot 2022-07-29 at 17 12 51" src="https://user-images.githubusercontent.com/48377058/181778926-987725cf-b961-407c-a917-de4a1af4e27c.png">

at NSEvent.go file

**Comment by bashery** [comment]
i think go bool match ```_Ctype_Bool``` not ```_Ctype_schar```

**Comment by sparkylein** [comment]
Hi nuxart,
I did your proposed changes and the objective-c errors went away, but the go errors remained.
The cause is that go doesn't like:

b = C.BOOL(1)

So I changed every line to:

b = C.BOOL(true)

and with this I got the hello.go sample to compile.

NICE!

**Comment by nuxart** [comment]
@sparkylein thanks, Itried your solution `b = C.BOOL(true)`, it still got error `cannot convert true (untyped bool constant) to type _Ctype_schar`

@bashery thanks for your testing

It looks cgo is not perfectly supported `bool`,  each processor architecture has different olution, so I decide use `int` instead, solution is:

```diff
-BOOL funcName(BOOL inputBool){
-     return YES;
-}

+ int funcName(int intputBool){
+   return 1;
+}
```

**Comment by sparkylein** [comment]
My go version:
go version go1.18.3 darwin/arm64

Not sure why you still get an error...

To recap:
I made all your proposed changes in:

NSEvent.m
NSEvent.go

and in 

NSPanel.go 

I changed each line you proposed to change to:

b = C.BOOL(true)

this is it.

I don't understand your error:
"cannot convert true (untyped bool constant) to type _Ctype_schar"

Maybe your files differ than GitHub master?

**Comment by nuxart** [comment]
@sparkylein  mine is  go version go1.18.4 darwin/amd64
`var c C.BOOL = C.BOOL(true)`
`cannot convert true (untyped bool constant) to type _Ctype_schar`

I think different `go env` makes different effect, not only go version, `clang/gccgo` version and `CGO_CFLAGS` also has effect

Do not use `bool` directly is safety

**Comment by sparkylein** [comment]
Good to know, thanks.

BTW:
Cloning GitHub master manually installs the fixed version, but doing:

go build hello.go

pulls-in the not-fixed version into go/pkg/mod/nuxui.org

**Comment by nuxart** [comment]
@sparkylein sure, I add a version to 0.0.8, and you can remove hello's go.mod file, then run `go mod init` -> `go mod tidy`, should be ok.

**Comment by sparkylein** [comment]
Cool, thanks.
